// Code generated by "cd scripts && go run . generate_route_ids". DO NOT EDIT.

package core

// APIRouteIDs numbers every API route so it can travel as two bytes instead of a path: once in a
// log prefix, once inside the packed aggregation key of user_logs.
//
// An ID is assigned once and never reused. A route that no longer exists keeps its number,
// annotated "retired", because rows already written still name it and handing that number to a
// different route would rewrite what those rows mean.
var APIRouteIDs = map[string]int16{
	"GET.agent-models":                1,
	"GET.backups":                     2,
	"GET.cash-bank-movement-by-id":    3,
	"GET.cash-banks":                  4,
	"GET.cash-banks-movements":        5,
	"GET.cash-banks-reconciliations":  6,
	"GET.client-provider":             7,
	"GET.client-provider-ids":         8,
	"GET.company-credit-budget":       110,
	"GET.company-credit-usage-detail": 107,
	"GET.company-credit-usage-report": 108,
	"GET.company-credit-usage-users":  109,
	"GET.company-parametros":          9,
	"GET.country-cities":              10,
	"GET.credit-usage":                11,
	"GET.cron-actions-scheduled":      12,
	"GET.ecommerce-page-content":      13,
	"GET.empresas":                    14,
	"GET.expense-schedule-periods":    15,
	"GET.expenses":                    16,
	"GET.expenses-scheduled":          17,
	"GET.gallery-images":              18,
	"GET.image-asset-text-search":     19,
	"GET.image-assets":                20,
	"GET.image-id-counter":            21,
	"GET.locations-warehouses":        22,
	"GET.observability":               105,
	"GET.p-company-names-by-ids":      23,
	"GET.p-dev-login":                 24,
	"GET.p-hello":                     25,
	"GET.p-product-text-search":       26,
	"GET.p-products-ecommerce":        27,
	"GET.p-products-ids":              28,
	"GET.p-webpage":                   29,
	"GET.parametros":                  30,
	"GET.perfiles":                    31,
	"GET.product-stock-lots-by-ids":   32,
	"GET.product-supply":              33,
	"GET.products":                    34,
	"GET.products-stock":              35,
	"GET.purchase-orders":             36,
	"GET.purchase-orders-query":       37,
	"GET.records-by-ids":              38,
	"GET.reload-login":                39,
	"GET.request-errors-by-ids":       106,
	"GET.sale-order-by-ids":           40,
	"GET.sale-order-query":            41,
	"GET.sale-orders":                 42,
	"GET.sale-summary":                43,
	"GET.sales-planning":              44,
	"GET.seasonality-curve":           45,
	"GET.server-metrics":              104,
	"GET.shared-lists":                46,
	"GET.shipping-costs":              47,
	"GET.supply-material":             48,
	"GET.system-memory-packages":      49,
	"GET.system-metrics-stream":       50,
	"GET.system-parameters":           51,
	"GET.users":                       52,
	"GET.users-ids":                   53,
	"GET.warehouse-movements":         54,
	"GET.warehouse-movements-grouped": 55,
	"GET.warehouse-product-stock":     56,
	"GET.webpage-pages":               57,
	"GET.website-config":              58,
	"POST.backup-create":              59,
	"POST.backup-restore":             60,
	"POST.cash-banks":                 61,
	"POST.cash-banks-movement":        62,
	"POST.cash-banks-reconciliation":  63,
	"POST.client-provider":            64,
	"POST.company":                    65,
	"POST.company-credit-budget":      111,
	"POST.company-parametros":         66,
	"POST.ecommerce-page-content":     67,
	"POST.expense-payment":            68,
	"POST.expenses":                   69,
	"POST.expenses-scheduled":         70,
	"POST.gallery-image":              71,
	"POST.initial-data":               72,
	"POST.p-agent-turn":               73,
	"POST.p-contact-message":          103,
	"POST.p-signup-company":           74,
	"POST.p-signup-request":           75,
	"POST.p-signup-verify":            76,
	"POST.p-user-login":               77,
	"POST.parametros":                 78,
	"POST.perfiles":                   79,
	"POST.product-category-image":     80,
	"POST.product-image":              81,
	"POST.product-supply":             82,
	"POST.productos-stock":            83,
	"POST.products":                   84,
	"POST.purchase-order-entry":       85,
	"POST.purchase-orders":            86,
	"POST.sale-order":                 87,
	"POST.sales-planning":             88,
	"POST.seasonality-curve":          89,
	"POST.shared-lists":               90,
	"POST.shipping-costs":             91,
	"POST.sites":                      92,
	"POST.supply-material":            93,
	"POST.system-parameters":          94,
	"POST.user-self":                  95,
	"POST.users":                      96,
	"POST.warehouses":                 97,
	"POST.webpage-page":               98,
	"POST.webpage-showcase-image":     99,
	"POST.website-domain":             100,
	"POST.website-seo":                101,
	"PUT.purchase-orders":             102,
}

// APIRouteNames reads an ID back into its route, for the dashboard and for anyone holding a log
// line with an "r118" token in it. Retired routes are included, which is the only thing that keeps
// an old row readable.
//
// Inverted at start rather than generated as a second literal: two maps in one file are two things
// that can disagree, and this one is exactly the first one backwards.
var APIRouteNames = make(map[int16]string, len(APIRouteIDs))

func init() {
	for route, id := range APIRouteIDs {
		APIRouteNames[id] = route
	}
}

// MaxAPIRouteID is the highest number handed out so far, retired routes included.
const MaxAPIRouteID int16 = 111

// APIRouteID resolves a "METHOD.route" path to its number. Zero means unknown — a 404, or a route
// added since the last generation — and is never a valid assignment.
func APIRouteID(funcPath string) int16 {
	return APIRouteIDs[funcPath]
}
