package handlers

import (
	"app/core"
	"app/db"
	s "app/types"
	"encoding/json"
	"fmt"
	"time"

	"golang.org/x/sync/errgroup"
)

func GetListasCompartidas(req *core.HandlerArgs) core.HandlerResponse {
	listasIDs := req.GetQueryIntSlice("ids")

	if len(listasIDs) == 0 {
		return req.MakeErr("No se enviaron los ids de las listas a consultar.")
	}

	listaRegistrosMap := map[int32]*[]s.ListaCompartidaRegistro{}
	for _, listaID := range listasIDs {
		listaRegistrosMap[listaID] = &[]s.ListaCompartidaRegistro{}
	}
	eg := errgroup.Group{}

	for _, listaID := range listasIDs {
		updated := req.GetQueryInt64(fmt.Sprintf("id_%v", listaID))

		eg.Go(func() error {
			query := db.Query(listaRegistrosMap[listaID])
			query.Select().
				EmpresaID.Equals(req.Usuario.EmpresaID).
				ListaID.Equals(listaID)
			if updated > 0 {
				query.Updated.GreaterThan(updated)
			} else {
				query.Status.Equals(1)
			}
			return query.Exec()
		})
	}

	if err := eg.Wait(); err != nil {
		return req.MakeErr(err)
	}

	response := map[string]*[]s.ListaCompartidaRegistro{}
	for id, registros := range listaRegistrosMap {
		response[fmt.Sprintf("id_%v", id)] = registros

		core.Log("Listas Compartidas Registros::", id, "|", len(*registros))
	}

	return core.MakeResponse(req, &response)
}

func PostListasCompartidas(req *core.HandlerArgs) core.HandlerResponse {

	records := []s.ListaCompartidaRegistro{}
	err := json.Unmarshal([]byte(*req.Body), &records)
	if err != nil {
		return req.MakeErr("Error al deserilizar el body: " + err.Error())
	}

	if len(records) == 0 {
		return req.MakeErr("No se recibieron registros para guardar.")
	}

	uniqueIncomingHashToIndex := map[int32]int{}
	uniqueIncomingHashes := []int32{}
	seenIncomingHashes := map[int32]bool{}
	
	// Track indices of records that need autoincrement (ID <= 0)
	newIDs := []s.NewIDToID{}
	
	for index := range records {
		e := &records[index]
		if len(e.Nombre) < 4 || e.ListaID == 0 {
			return req.MakeErr("Faltan propiedades de en uno de los registros.")
		}
		
		newIDs = append(newIDs, s.NewIDToID{TempID: e.ID})

		// Keep NombreHash consistent with table SelfParse logic.
		e.SelfParse()
		if previousIndex, duplicateHashExists := uniqueIncomingHashToIndex[e.NombreHash]; duplicateHashExists {
			previousRecordName := records[previousIndex].Nombre
			return req.MakeErr(fmt.Sprintf(
				"Hay registros repetidos por nombre en el mismo envío para la lista %v: \"%s\" y \"%s\".",
				e.ListaID, previousRecordName, e.Nombre,
			))
		}
		
		uniqueIncomingHashToIndex[e.NombreHash] = index
		if !seenIncomingHashes[e.NombreHash] {
			uniqueIncomingHashes = append(uniqueIncomingHashes, e.NombreHash)
			seenIncomingHashes[e.NombreHash] = true
		}
	}

	// Check collisions for all incoming hashes (new and existing records).
	existingRecordsByHash := []s.ListaCompartidaRegistro{}
	existingRecordsQuery := db.Query(&existingRecordsByHash)
	existingRecordsQuery.Select().
		EmpresaID.Equals(req.Usuario.EmpresaID).NombreHash.In(uniqueIncomingHashes...).AllowFilter()
	
	if err = existingRecordsQuery.Exec(); err != nil {
		return req.MakeErr("Error al consultar registros existentes de lista compartida: " + err.Error())
	}

	existingRecordsGroupedByHash := core.SliceToMapP(existingRecordsByHash, 
		func(e s.ListaCompartidaRegistro) int32 { return e.NombreHash })

	nowTime := time.Now().Unix()
	
	for index := range records {
		incomingRecord := &records[index]
		incomingRecord.EmpresaID = req.Usuario.EmpresaID
		incomingRecord.Updated = nowTime
		incomingRecord.UpdatedBy = req.Usuario.ID
		
		collidingExistingRecords := existingRecordsGroupedByHash[incomingRecord.NombreHash]
		reusableDeletedRecordID := int32(0)

		for _, existingRecord := range collidingExistingRecords {
			isSameRecord := incomingRecord.ID > 0 && incomingRecord.ID == existingRecord.ID
			if isSameRecord {
				continue
			}
			if existingRecord.Status > 0 {
				return req.MakeErr(fmt.Sprintf(
					"El nombre \"%s\" ya existe en la lista %v.",
					incomingRecord.Nombre,
					incomingRecord.ListaID,
				))
			}
			if incomingRecord.ID <= 0 && reusableDeletedRecordID == 0 {
				reusableDeletedRecordID = existingRecord.ID
			}
		}

		// Reuse a deleted row ID so client inserts become upserts by historical name.
		if incomingRecord.ID <= 0 && reusableDeletedRecordID > 0 {
			core.Log("PostListasCompartidas:: reutilizando ID por NombreHash", incomingRecord.ListaID, incomingRecord.NombreHash, reusableDeletedRecordID)
			incomingRecord.ID = reusableDeletedRecordID
		}
	}

	if err = db.Insert(&records); err != nil {
		return req.MakeErr("Error al actualizar / insertar el registro de lista compartida: " + err.Error())
	}

	// Update newIDs with the actual IDs generated by the ORM
	for i := range records {
		newIDs[i].NewID = records[i].ID
	}

	return req.MakeResponse(newIDs)
}
