package handlers

import (
	"app/core"
	"app/db"
	s "app/types"
	"encoding/json"
	"fmt"
	"time"

	"golang.org/x/sync/errgroup"
)

func GetListasCompartidas(req *core.HandlerArgs) core.HandlerResponse {
	listasIDs := req.GetQueryIntSlice("ids")

	if len(listasIDs) == 0 {
		return req.MakeErr("No se enviaron los ids de las listas a consultar.")
	}

	listaRegistrosMap := map[int32]*[]s.ListaCompartidaRegistro{}
	for _, listaID := range listasIDs {
		listaRegistrosMap[listaID] = &[]s.ListaCompartidaRegistro{}
	}
	eg := errgroup.Group{}

	for _, listaID := range listasIDs {
		updated := req.GetQueryInt64(fmt.Sprintf("id_%v", listaID))

		eg.Go(func() error {
			query := db.Query(listaRegistrosMap[listaID])
			query.Select().
				EmpresaID.Equals(req.Usuario.EmpresaID).
				ListaID.Equals(listaID)
			if updated > 0 {
				query.Updated.GreaterThan(updated)
			} else {
				query.Status.Equals(1)
			}
			return query.Exec()
		})
	}

	if err := eg.Wait(); err != nil {
		return req.MakeErr(err)
	}

	response := map[string]*[]s.ListaCompartidaRegistro{}
	for id, registros := range listaRegistrosMap {
		response[fmt.Sprintf("id_%v", id)] = registros

		core.Log("Listas Compartidas Registros::", id, "|", len(*registros))
	}

	return core.MakeResponse(req, &response)
}

func PostListasCompartidas(req *core.HandlerArgs) core.HandlerResponse {

	records := []s.ListaCompartidaRegistro{}
	err := json.Unmarshal([]byte(*req.Body), &records)
	if err != nil {
		return req.MakeErr("Error al deserilizar el body: " + err.Error())
	}

	for _, e := range records {
		if len(e.Nombre) < 4 || e.ListaID == 0 {
			return req.MakeErr("Faltan propiedades de en uno de los registros.")
		}
	}

	nowTime := time.Now().Unix()
	// Track indices of records that need autoincrement (ID <= 0)
	recordsNeedingAutoincrement := []int{}
	for i, e := range records {
		if e.ID <= 0 {
			recordsNeedingAutoincrement = append(recordsNeedingAutoincrement, i)
		}
	}

	// Store original IDs for these records
	originalIDs := []s.NewIDToID{}
	for _, idx := range recordsNeedingAutoincrement {
		originalIDs = append(originalIDs, s.NewIDToID{
			NewID: records[idx].ID,
			TempID: records[idx].ID,
		})
	}

	for i := range records {
		records[i].EmpresaID = req.Usuario.EmpresaID
		records[i].Updated = nowTime
		records[i].UpdatedBy = req.Usuario.ID
		// Autoincrement is handled automatically by the ORM via handlePreInsert
		// Records with ID <= 0 will get autoincremented
	}

	if err = db.Insert(&records); err != nil {
		return req.MakeErr("Error al actualizar / insertar el registro de lista compartida: " + err.Error())
	}

	// Update newIDs with the actual IDs generated by the ORM
	newIDs := []s.NewIDToID{}
	for i, idx := range recordsNeedingAutoincrement {
		newIDs = append(newIDs, s.NewIDToID{
			NewID:  records[idx].ID,
			TempID: originalIDs[i].TempID,
		})
	}

	return req.MakeResponse(newIDs)
}
