package handlers

import (
	"app/comercial"
	"app/core"
	"app/negocio"
)

var ModuleHandlers = core.AppRouterType{
	"GET.p-hello":                   HelloWorld,
	"POST.p-user-login":             PostLogin,
	"GET.reload-login":              ReloadLogin,
	"GET.empresas":                  GetEmpresas,
	"GET.empresa-parametros":        GetEmpresaParametros,
	"POST.empresa-parametros":       PostEmpresaParametros,
	"POST.empresa":                  PostEmpresa,
	"GET.usuarios":                  GetUsuarios,
	"GET.usuarios-ids":              GetUsuariosByIDs,
	"POST.usuarios":                 PostUsuarios,
	"POST.usuario-propio":           PostUsuarios,
	"POST.seguridad-accesos":        PostAcceso,
	"GET.seguridad-accesos":         GetAccesos,
	"POST.perfiles":                 PostPerfiles,
	"GET.perfiles":                  GetPerfiles,
	"GET.sedes-almacenes":           GetSedesAlmacenes,
	"GET.pais-ciudades":             GetPaisCiudades,
	"POST.sedes":                    PostSedes,
	"POST.almacenes":                PostAlmacen,
	"GET.productos":                 GetProductos,
	"GET.p-productos-ids":           GetProductosByIDs,
	"GET.p-productos-cms":           GetProductosCMS,
	"GET.p-productos-index":         GetProductsIndex,
	"GET.p-productos-index-delta":   GetProductsIndexDelta,
	"POST.productos":                PostProductos,
	"POST.producto-image":           PostProductoImage,
	"POST.producto-categoria-image": PostProductoCategoriaImage,
	"GET.listas-compartidas":        GetListasCompartidas,
	"POST.listas-compartidas":       PostListasCompartidas,
	"POST.images":                   PostImage,
	"GET.cajas":                     GetCajas,
	"POST.cajas":                    PostCajas,
	"GET.caja-movimientos":          GetCajaMovimientos,
	"GET.caja-cuadres":              GetCajaCuadres,
	"POST.caja-cuadre":              PostCajaCuadre,
	"POST.caja-movimiento":          PostMovimientoCaja,
	"POST.sale_order":               comercial.PostSaleOrder,
	"GET.sale_orders":               comercial.GetSaleOrders,
	"GET.sale_summary":              comercial.GetSaleSummary,
	"GET.p-demo-serialization":      Demo1,
	"POST.galeria-image":            PostGaleriaImage,
	"GET.galeria-images":            GetGaleriaImages,
	"POST.parametros":               PostParametros,
	"GET.parametros":                GetParametros,
	"GET.system-parameters":         GetSystemParameters,
	"POST.system-parameters":        PostSystemParameters,
	"GET.system-metrics-stream":     GetSystemMetricsStream,
	"GET.system-memory-packages":    GetSystemMemoryPackages,
	"GET.entities":                  negocio.GetEntities,
	"POST.entities":                 negocio.PostEntities,
}
