package handlers

import "app/core"

var ModuleHandlers = core.AppRouterType{
	"GET.p-hello":                   HelloWorld,
	"POST.p-user-login":             PostLogin,
	"GET.reload-login":              ReloadLogin,
	"GET.empresas":                  GetEmpresas,
	"GET.empresa-parametros":        GetEmpresaParametros,
	"POST.empresa-parametros":       PostEmpresaParametros,
	"POST.empresa":                  PostEmpresa,
	"GET.usuarios":                  GetUsuarios,
	"POST.usuarios":                 PostUsuarios,
	"POST.usuario-propio":           PostUsuarios,
	"POST.seguridad-accesos":        PostAcceso,
	"GET.seguridad-accesos":         GetAccesos,
	"POST.perfiles":                 PostPerfiles,
	"GET.perfiles":                  GetPerfiles,
	"GET.sedes-almacenes":           GetSedesAlmacenes,
	"GET.pais-ciudades":             GetPaisCiudades,
	"POST.sedes":                    PostSedes,
	"POST.almacenes":                PostAlmacen,
	"GET.productos":                 GetProductos,
	"GET.p-productos-cms":           GetProductosCMS,
	"POST.productos":                PostProductos,
	"POST.producto-image":           PostProductoImage,
	"POST.producto-categoria-image": PostProductoCategoriaImage,
	"GET.listas-compartidas":        GetListasCompartidas,
	"POST.listas-compartidas":       PostListasCompartidas,
	"POST.images":                   PostImage,
	"GET.cajas":                     GetCajas,
	"POST.cajas":                    PostCajas,
	"GET.caja-movimientos":          GetCajaMovimientos,
	"GET.caja-cuadres":              GetCajaCuadres,
	"POST.caja-cuadre":              PostCajaCuadre,
	"POST.caja-movimiento":          PostMovimientoCaja,
	"GET.p-demo-serialization":      Demo1,
	"POST.galeria-image":            PostGaleriaImage,
	"GET.galeria-images":            GetGaleriaImages,
	"POST.parametros":               PostParametros,
	"GET.parametros":                GetParametros,
	"GET.system-parameters":         GetSystemParameters,
	"POST.system-parameters":        PostSystemParameters,
}
