/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generate-sections.ts
 */
import FeatureListSimple, { schema as Schema0 } from './templates/features/FeatureListSimple.svelte';
import ProductGridSimple, { schema as Schema1 } from './templates/products/ProductGridSimple.svelte';
import HeroStandard, { schema as Schema2 } from './templates/hero/HeroStandard.svelte';

import type { ComponentType } from 'svelte';
import type { SectionSchema } from '../renderer/section-types';

export interface RegistryEntry {
  component: ComponentType;
  schema: SectionSchema;
}

export const SectionRegistry: Record<string, RegistryEntry> = {
  'FeatureListSimple': { component: FeatureListSimple, schema: Schema0 },
  'ProductGridSimple': { component: ProductGridSimple, schema: Schema1 },
  'HeroStandard': { component: HeroStandard, schema: Schema2 },
};

export const SectionList = Object.keys(SectionRegistry).map(key => ({
  id: key,
  name: SectionRegistry[key].schema.name,
  category: SectionRegistry[key].schema.category
}));
