// Code generated by scripts/controllers/controllers_generator.go; DO NOT EDIT.
package exec

import (
	agentTypes "app/agent/types"
	salesTypes "app/sales/types"
	configTypes "app/config/types"
	"app/core"
	coreTypes "app/core/types"
	"app/db"
	financeTypes "app/finance/types"
	logisticsTypes "app/logistics/types"
	businessTypes "app/business/types"
	securityTypes "app/security/types"
)

func MakeScyllaControllers() []db.ScyllaControllerInterface {
	return []db.ScyllaControllerInterface{
		makeDBController[DemoStruct](),
		makeDBController[agentTypes.AgentMessage](),
		makeDBController[salesTypes.ProductSaleSummary](),
		makeDBController[salesTypes.SaleOrder](),
		makeDBController[salesTypes.SaleSummary](),
		makeDBController[salesTypes.ShippingCost](),
		makeDBController[configTypes.Company](),
		makeDBController[configTypes.Parametros](),
		makeDBController[configTypes.SystemParameters](),
		makeDBController[core.Cache](),
		makeDBController[core.CronAction](),
		makeDBController[coreTypes.UsageLog](),
		makeDBController[coreTypes.User](),
		makeDBController[financeTypes.CashBank](),
		makeDBController[financeTypes.CashReconciliation](),
		makeDBController[financeTypes.CashBankMovement](),
		makeDBController[logisticsTypes.DeliveryOrderNote](),
		makeDBController[logisticsTypes.ProductStock](),
		makeDBController[logisticsTypes.ProductStockDetail](),
		makeDBController[logisticsTypes.ProductStockLot](),
		makeDBController[logisticsTypes.ProductSupply](),
		makeDBController[logisticsTypes.PurchaseOrder](),
		makeDBController[logisticsTypes.SupplyMaterial](),
		makeDBController[logisticsTypes.WarehouseProductMovement](),
		makeDBController[businessTypes.Warehouse](),
		makeDBController[businessTypes.ClientProvider](),
		makeDBController[businessTypes.GalleryImage](),
		makeDBController[businessTypes.SharedListRecord](),
		makeDBController[businessTypes.CityLocation](),
		makeDBController[businessTypes.Product](),
		makeDBController[businessTypes.Site](),
		makeDBController[securityTypes.Profile](),
	}
}
