// Code generated by scripts/controllers/controllers_generator.go; DO NOT EDIT.
package exec

import (
	agentTypes "app/agent/types"
	businessTypes "app/business/types"
	configTypes "app/config/types"
	"app/core"
	coreTypes "app/core/types"
	"app/db"
	financeTypes "app/finance/types"
	logisticsTypes "app/logistics/types"
	salesTypes "app/sales/types"
	securityTypes "app/security/types"
	webpageTypes "app/webpage/types"
)

func MakeScyllaControllers() []db.Controller {
	return []db.Controller{
		makeDBController[DemoStruct](),
		makeDBController[agentTypes.AgentMessage](),
		makeDBController[businessTypes.CityLocation](),
		makeDBController[businessTypes.ClientProvider](),
		makeDBController[businessTypes.GalleryImage](),
		makeDBController[businessTypes.ImageAsset](),
		makeDBController[businessTypes.ImageAssetCategory](),
		makeDBController[businessTypes.Product](),
		makeDBController[businessTypes.SharedListRecord](),
		makeDBController[businessTypes.Site](),
		makeDBController[businessTypes.Warehouse](),
		makeDBController[configTypes.Company](),
		makeDBController[configTypes.Parameters](),
		makeDBController[configTypes.SystemParameters](),
		makeDBController[core.Cache](),
		makeDBController[core.CronAction](),
		makeDBController[core.GlobalCache](),
		makeDBController[coreTypes.CreditUsage](),
		makeDBController[coreTypes.UsageLog](),
		makeDBController[coreTypes.User](),
		makeDBController[financeTypes.CashBank](),
		makeDBController[financeTypes.CashBankMovement](),
		makeDBController[financeTypes.CashReconciliation](),
		makeDBController[financeTypes.Expense](),
		makeDBController[financeTypes.ExpenseScheduled](),
		makeDBController[logisticsTypes.DeliveryOrderNote](),
		makeDBController[logisticsTypes.ProductStock](),
		makeDBController[logisticsTypes.ProductStockDetail](),
		makeDBController[logisticsTypes.ProductStockLot](),
		makeDBController[logisticsTypes.ProductSupply](),
		makeDBController[logisticsTypes.PurchaseOrder](),
		makeDBController[logisticsTypes.SupplyMaterial](),
		makeDBController[logisticsTypes.WarehouseProductMovement](),
		makeDBController[salesTypes.ProductSaleSummary](),
		makeDBController[salesTypes.SaleOrder](),
		makeDBController[salesTypes.SalesPlanning](),
		makeDBController[salesTypes.SeasonalityCurve](),
		makeDBController[salesTypes.ShippingCost](),
		makeDBController[securityTypes.Profile](),
		makeDBController[securityTypes.SignUpRequest](),
		makeDBController[webpageTypes.EcommercePageContent](),
		makeDBController[webpageTypes.Webpage](),
	}
}

// Resolves table names for db.QueryCachedGenericByIDs.
func init() {
	db.RegisterTableFactory("zz_demo_struct", func() db.Table { return db.MakeTable[DemoStruct]() })
	db.RegisterTableFactory("agent_messages", func() db.Table { return db.MakeTable[agentTypes.AgentMessage]() })
	db.RegisterTableFactory("city_locations", func() db.Table { return db.MakeTable[businessTypes.CityLocation]() })
	db.RegisterTableFactory("client_provider", func() db.Table { return db.MakeTable[businessTypes.ClientProvider]() })
	db.RegisterTableFactory("gallery_images", func() db.Table { return db.MakeTable[businessTypes.GalleryImage]() })
	db.RegisterTableFactory("image_assets", func() db.Table { return db.MakeTable[businessTypes.ImageAsset]() })
	db.RegisterTableFactory("image_assets_category", func() db.Table { return db.MakeTable[businessTypes.ImageAssetCategory]() })
	db.RegisterTableFactory("products", func() db.Table { return db.MakeTable[businessTypes.Product]() })
	db.RegisterTableFactory("shared_list_records", func() db.Table { return db.MakeTable[businessTypes.SharedListRecord]() })
	db.RegisterTableFactory("sites", func() db.Table { return db.MakeTable[businessTypes.Site]() })
	db.RegisterTableFactory("warehouses", func() db.Table { return db.MakeTable[businessTypes.Warehouse]() })
	db.RegisterTableFactory("companies", func() db.Table { return db.MakeTable[configTypes.Company]() })
	db.RegisterTableFactory("parameters", func() db.Table { return db.MakeTable[configTypes.Parameters]() })
	db.RegisterTableFactory("system_parameters", func() db.Table { return db.MakeTable[configTypes.SystemParameters]() })
	db.RegisterTableFactory("cache", func() db.Table { return db.MakeTable[core.Cache]() })
	db.RegisterTableFactory("cron_actions", func() db.Table { return db.MakeTable[core.CronAction]() })
	db.RegisterTableFactory("cache_global", func() db.Table { return db.MakeTable[core.GlobalCache]() })
	db.RegisterTableFactory("credit_usage", func() db.Table { return db.MakeTable[coreTypes.CreditUsage]() })
	db.RegisterTableFactory("usage_log", func() db.Table { return db.MakeTable[coreTypes.UsageLog]() })
	db.RegisterTableFactory("users", func() db.Table { return db.MakeTable[coreTypes.User]() })
	db.RegisterTableFactory("cash_banks", func() db.Table { return db.MakeTable[financeTypes.CashBank]() })
	db.RegisterTableFactory("cash_bank_movements", func() db.Table { return db.MakeTable[financeTypes.CashBankMovement]() })
	db.RegisterTableFactory("cash_reconciliations", func() db.Table { return db.MakeTable[financeTypes.CashReconciliation]() })
	db.RegisterTableFactory("expenses", func() db.Table { return db.MakeTable[financeTypes.Expense]() })
	db.RegisterTableFactory("expenses_scheduled", func() db.Table { return db.MakeTable[financeTypes.ExpenseScheduled]() })
	db.RegisterTableFactory("delivery_order_note", func() db.Table { return db.MakeTable[logisticsTypes.DeliveryOrderNote]() })
	db.RegisterTableFactory("warehouse_product_stock", func() db.Table { return db.MakeTable[logisticsTypes.ProductStock]() })
	db.RegisterTableFactory("warehouse_product_stock_detail", func() db.Table { return db.MakeTable[logisticsTypes.ProductStockDetail]() })
	db.RegisterTableFactory("product_stock_lot", func() db.Table { return db.MakeTable[logisticsTypes.ProductStockLot]() })
	db.RegisterTableFactory("product_supply", func() db.Table { return db.MakeTable[logisticsTypes.ProductSupply]() })
	db.RegisterTableFactory("purchase_order", func() db.Table { return db.MakeTable[logisticsTypes.PurchaseOrder]() })
	db.RegisterTableFactory("supply_material", func() db.Table { return db.MakeTable[logisticsTypes.SupplyMaterial]() })
	db.RegisterTableFactory("warehouse_product_movement", func() db.Table { return db.MakeTable[logisticsTypes.WarehouseProductMovement]() })
	db.RegisterTableFactory("product_sale_summary", func() db.Table { return db.MakeTable[salesTypes.ProductSaleSummary]() })
	db.RegisterTableFactory("sale_order", func() db.Table { return db.MakeTable[salesTypes.SaleOrder]() })
	db.RegisterTableFactory("sales_planning", func() db.Table { return db.MakeTable[salesTypes.SalesPlanning]() })
	db.RegisterTableFactory("seasonality_curve", func() db.Table { return db.MakeTable[salesTypes.SeasonalityCurve]() })
	db.RegisterTableFactory("shipping_costs", func() db.Table { return db.MakeTable[salesTypes.ShippingCost]() })
	db.RegisterTableFactory("profiles", func() db.Table { return db.MakeTable[securityTypes.Profile]() })
	db.RegisterTableFactory("sign_up_requests", func() db.Table { return db.MakeTable[securityTypes.SignUpRequest]() })
	db.RegisterTableFactory("ecommerce_page_content", func() db.Table { return db.MakeTable[webpageTypes.EcommercePageContent]() })
	db.RegisterTableFactory("webpages", func() db.Table { return db.MakeTable[webpageTypes.Webpage]() })
}
