// Code generated by scripts/controllers/controllers_generator.go; DO NOT EDIT.
package exec

import (
	agentTypes "app/agent/types"
	businessTypes "app/business/types"
	configTypes "app/config/types"
	"app/core"
	coreTypes "app/core/types"
	financeTypes "app/finance/types"
	logisticsTypes "app/logistics/types"
	salesTypes "app/sales/types"
	securityTypes "app/security/types"
	webpageTypes "app/webpage/types"
	"github.com/ivanjoz/genix-orm/scylla"
)

func MakeScyllaControllers() []scylla.ScyllaControllerInterface {
	return []scylla.ScyllaControllerInterface{
		makeDBController[DemoStruct](),
		makeDBController[agentTypes.AgentMessage](),
		makeDBController[businessTypes.CityLocation](),
		makeDBController[businessTypes.ClientProvider](),
		makeDBController[businessTypes.GalleryImage](),
		makeDBController[businessTypes.ImageAsset](),
		makeDBController[businessTypes.ImageAssetCategory](),
		makeDBController[businessTypes.Product](),
		makeDBController[businessTypes.SharedListRecord](),
		makeDBController[businessTypes.Site](),
		makeDBController[businessTypes.Warehouse](),
		makeDBController[configTypes.Company](),
		makeDBController[configTypes.Parameters](),
		makeDBController[configTypes.SystemParameters](),
		makeDBController[core.Cache](),
		makeDBController[core.CronAction](),
		makeDBController[core.GlobalCache](),
		makeDBController[coreTypes.UsageLog](),
		makeDBController[coreTypes.User](),
		makeDBController[financeTypes.CashBank](),
		makeDBController[financeTypes.CashBankMovement](),
		makeDBController[financeTypes.CashReconciliation](),
		makeDBController[financeTypes.Expense](),
		makeDBController[financeTypes.ExpenseScheduled](),
		makeDBController[logisticsTypes.DeliveryOrderNote](),
		makeDBController[logisticsTypes.ProductStock](),
		makeDBController[logisticsTypes.ProductStockDetail](),
		makeDBController[logisticsTypes.ProductStockLot](),
		makeDBController[logisticsTypes.ProductSupply](),
		makeDBController[logisticsTypes.PurchaseOrder](),
		makeDBController[logisticsTypes.SupplyMaterial](),
		makeDBController[logisticsTypes.WarehouseProductMovement](),
		makeDBController[salesTypes.ProductSaleSummary](),
		makeDBController[salesTypes.SaleOrder](),
		makeDBController[salesTypes.SaleSummary](),
		makeDBController[salesTypes.SalesPlanning](),
		makeDBController[salesTypes.SeasonalityCurve](),
		makeDBController[salesTypes.ShippingCost](),
		makeDBController[securityTypes.Profile](),
		makeDBController[webpageTypes.EcommercePageContent](),
		makeDBController[webpageTypes.Webpage](),
	}
}

// Resolves table names for scylla.QueryCachedGenericByIDs.
func init() {
	scylla.RegisterTableFactory("zz_demo_struct", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[DemoStruct]() })
	scylla.RegisterTableFactory("agent_messages", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[agentTypes.AgentMessage]() })
	scylla.RegisterTableFactory("city_locations", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[businessTypes.CityLocation]() })
	scylla.RegisterTableFactory("client_provider", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[businessTypes.ClientProvider]() })
	scylla.RegisterTableFactory("gallery_images", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[businessTypes.GalleryImage]() })
	scylla.RegisterTableFactory("image_assets", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[businessTypes.ImageAsset]() })
	scylla.RegisterTableFactory("image_assets_category", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[businessTypes.ImageAssetCategory]() })
	scylla.RegisterTableFactory("products", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[businessTypes.Product]() })
	scylla.RegisterTableFactory("shared_list_records", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[businessTypes.SharedListRecord]() })
	scylla.RegisterTableFactory("sites", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[businessTypes.Site]() })
	scylla.RegisterTableFactory("warehouses", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[businessTypes.Warehouse]() })
	scylla.RegisterTableFactory("companies", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[configTypes.Company]() })
	scylla.RegisterTableFactory("parameters", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[configTypes.Parameters]() })
	scylla.RegisterTableFactory("system_parameters", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[configTypes.SystemParameters]() })
	scylla.RegisterTableFactory("cache", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[core.Cache]() })
	scylla.RegisterTableFactory("cron_actions", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[core.CronAction]() })
	scylla.RegisterTableFactory("cache_global", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[core.GlobalCache]() })
	scylla.RegisterTableFactory("usage_log", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[coreTypes.UsageLog]() })
	scylla.RegisterTableFactory("users", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[coreTypes.User]() })
	scylla.RegisterTableFactory("cash_banks", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[financeTypes.CashBank]() })
	scylla.RegisterTableFactory("cash_bank_movements", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[financeTypes.CashBankMovement]() })
	scylla.RegisterTableFactory("cash_reconciliations", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[financeTypes.CashReconciliation]() })
	scylla.RegisterTableFactory("expenses", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[financeTypes.Expense]() })
	scylla.RegisterTableFactory("expenses_scheduled", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[financeTypes.ExpenseScheduled]() })
	scylla.RegisterTableFactory("delivery_order_note", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[logisticsTypes.DeliveryOrderNote]() })
	scylla.RegisterTableFactory("warehouse_product_stock", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[logisticsTypes.ProductStock]() })
	scylla.RegisterTableFactory("warehouse_product_stock_detail", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[logisticsTypes.ProductStockDetail]() })
	scylla.RegisterTableFactory("product_stock_lot", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[logisticsTypes.ProductStockLot]() })
	scylla.RegisterTableFactory("product_supply", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[logisticsTypes.ProductSupply]() })
	scylla.RegisterTableFactory("purchase_order", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[logisticsTypes.PurchaseOrder]() })
	scylla.RegisterTableFactory("supply_material", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[logisticsTypes.SupplyMaterial]() })
	scylla.RegisterTableFactory("warehouse_product_movement", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[logisticsTypes.WarehouseProductMovement]() })
	scylla.RegisterTableFactory("product_sale_summary", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[salesTypes.ProductSaleSummary]() })
	scylla.RegisterTableFactory("sale_order", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[salesTypes.SaleOrder]() })
	scylla.RegisterTableFactory("sale_summary", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[salesTypes.SaleSummary]() })
	scylla.RegisterTableFactory("sales_planning", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[salesTypes.SalesPlanning]() })
	scylla.RegisterTableFactory("seasonality_curve", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[salesTypes.SeasonalityCurve]() })
	scylla.RegisterTableFactory("shipping_costs", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[salesTypes.ShippingCost]() })
	scylla.RegisterTableFactory("profiles", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[securityTypes.Profile]() })
	scylla.RegisterTableFactory("ecommerce_page_content", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[webpageTypes.EcommercePageContent]() })
	scylla.RegisterTableFactory("webpages", func() scylla.ScyllaTable { return scylla.MakeScyllaTable[webpageTypes.Webpage]() })
}
