/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generate-sections.ts
 */
import HtmlSection, { schema as Schema0 } from './html/HtmlSection.svelte';
import FeatureListSimple, { schema as Schema1 } from './features/FeatureListSimple.svelte';
import HeroStandard, { schema as Schema2 } from './hero/HeroStandard.svelte';
import ProductGridSimple, { schema as Schema3 } from './products/ProductGridSimple.svelte';

import type { Component } from 'svelte';
import type { SectionSchema } from '../renderer/section-types';

export interface RegistryEntry {
  component: Component<any>;
  schema: SectionSchema;
}

export const SectionRegistry: Record<string, RegistryEntry> = {
  'HtmlSection': { component: HtmlSection, schema: Schema0 },
  'FeatureListSimple': { component: FeatureListSimple, schema: Schema1 },
  'HeroStandard': { component: HeroStandard, schema: Schema2 },
  'ProductGridSimple': { component: ProductGridSimple, schema: Schema3 },
};

export const SectionList = Object.keys(SectionRegistry).map(key => ({
  id: key,
  name: SectionRegistry[key].schema.name,
  category: SectionRegistry[key].schema.category
}));
