import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Paths relative to the project root or script location
const SECTIONS_ROOT = path.resolve(__dirname, '../pkg-store/sections/templates');
const OUTPUT_FILE = path.resolve(__dirname, '../pkg-store/sections/registry.ts');

function generateRegistry() {
  console.log('🚀 Generating Section Registry...');
  
  const sections: { name: string; path: string; category: string }[] = [];

  function walk(dir: string, category: string = '') {
    const files = fs.readdirSync(dir);
    
    for (const file of files) {
      const fullPath = path.join(dir, file);
      const stat = fs.statSync(fullPath);
      
      if (stat.isDirectory()) {
        walk(fullPath, category || file);
      } else if (file.endsWith('.svelte')) {
        const componentName = file.replace('.svelte', '');
        const relativePath = './' + path.relative(path.dirname(OUTPUT_FILE), fullPath);
        sections.push({
          name: componentName,
          path: relativePath,
          category: category
        });
      }
    }
  }

  if (!fs.existsSync(SECTIONS_ROOT)) {
    console.error(`❌ Sections directory not found: ${SECTIONS_ROOT}`);
    return;
  }

  walk(SECTIONS_ROOT);

  const imports = sections
    .map((s, i) => `import ${s.name}, { schema as Schema${i} } from '${s.path}';`)
    .join('\n');

  const registryEntries = sections
    .map((s, i) => `  '${s.name}': { component: ${s.name}, schema: Schema${i} },`)
    .join('\n');

  const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generate-sections.ts
 */
${imports}

import type { ComponentType } from 'svelte';
import type { SectionSchema } from '../renderer/section-types';

export interface RegistryEntry {
  component: ComponentType;
  schema: SectionSchema;
}

export const SectionRegistry: Record<string, RegistryEntry> = {
${registryEntries}
};

export const SectionList = Object.keys(SectionRegistry).map(key => ({
  id: key,
  name: SectionRegistry[key].schema.name,
  category: SectionRegistry[key].schema.category
}));
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`✅ Registry generated at: ${OUTPUT_FILE}`);
}

generateRegistry();
