// Constants mirror the backend binary contract for text and taxonomy payloads.
export const TEXT_BINARY_MAGIC = "GIXIDX01";
export const TEXT_BINARY_VERSION = 2;
export const TAXONOMY_BINARY_MAGIC = "GIXTAX01";
export const TAXONOMY_BINARY_VERSION = 2;

// Text sections are fixed and validated in the decoder.
export const TEXT_SECTION_DICTIONARY = 1;
export const TEXT_SECTION_SHAPES = 2;
export const TEXT_SECTION_CONTENT = 3;

// Taxonomy sections are fixed and validated in the decoder.
export const TAXONOMY_SECTION_BRAND_IDS = 1;
export const TAXONOMY_SECTION_BRAND_NAMES = 2;
export const TAXONOMY_SECTION_CATEGORY_IDS = 3;
export const TAXONOMY_SECTION_CATEGORY_NAMES = 4;
export const TAXONOMY_SECTION_BRAND_INDEXES = 5;
export const TAXONOMY_SECTION_CATEGORY_COUNTS = 6;
export const TAXONOMY_SECTION_CATEGORY_INDEX = 7;

// Brand index encoding flags are generated by backend taxonomy pass.
export const BRAND_INDEX_ENCODING_UINT12 = 1;
export const BRAND_INDEX_ENCODING_UINT16 = 2;

// Decoded product row including attached taxonomy references.
export interface DecodedRecord {
	recordIndex: number;
	shape: number[];
	text: string;
	brandDictionaryIndex: number;
	brandID: number;
	brandName: string;
	categoryDictionaryIndexes: number[];
	categoryIDs: number[];
	categoryNames: string[];
}

// Decoded taxonomy block in columnar form.
export interface DecodedTaxonomy {
	brandIDs: number[];
	brandNames: string[];
	categoryIDs: number[];
	categoryNames: string[];
	productBrandDictionaryIndex: number[];
	productCategoryCounts: number[];
	productCategoryIndexes: number[];
	brandIndexEncodingFlag: number;
}

// Decoder operational stats used for debug and observability.
export interface DecodeStats {
	recordCount: number;
	dictionaryCount: number;
	dictionaryBytes: number;
	shapesBytes: number;
	contentBytes: number;
	shapeDelta8Count: number;
	shapeDelta16Count: number;
	shapeDelta24Count: number;
	taxonomyBytes: number;
	taxonomyBrandCount: number;
	taxonomyCategoryCount: number;
	taxonomyBrandIndexMode: string;
}

// Top-level decoded payload for web consumption.
export interface DecodeResult {
	dictionaryTokens: string[];
	records: DecodedRecord[];
	taxonomy: DecodedTaxonomy | null;
	stats: DecodeStats;
}

