// Feature copy for the public /welcome page. Each string is `English|Spanish` for T.svelte.
// Items are deliberately short labels, not sentences: the page shows eight lists at once and a
// visitor scans them. The reasoning behind each one lives in docs/PAGE_CONTENT.md.
// `available` is what works today; `pending` is announced but not built, and the page marks it with
// its own icon. The state of each item must match the roadmap in README.md.
export interface IFeatureSection {
  id: string
  icon: string
  illustration: string
  title: string
  lead: string
  available: string[]
  pending: string[]
}

export const featureSections: IFeatureSection[] = [
  {
    id: 'feature-products',
    icon: 'icon-[fa--cubes]',
    illustration: '/images/feature-products.svg',
    title: 'Products, services, and materials|Productos, servicios e insumos',
    lead: 'One catalog for the counter, the warehouse, and the store. And if you manufacture, this is where your production process and the real cost of each unit are mapped.|Un solo catálogo para el mostrador, el almacén y la tienda. Y si usted fabrica, aquí se mapea su proceso productivo y el costo real de cada unidad.',
    available: [
      'Catalog with categories, brands, and attributes|Catálogo con categorías, marcas y atributos',
      'Several presentations and prices per product|Varias presentaciones y precios por producto',
      'SKU, lot, and serial number|SKU, lote y número de serie',
      'Sub-units: buy by the box, sell by the unit|Sub-unidades: compre por caja, venda por unidad',
      'Materials and supplies with their suppliers|Insumos y materiales con sus proveedores',
      'Materials bought in the purchase order|Compra de insumos en la orden de compra',
      'Bulk import and export through Excel|Carga y descarga masiva desde Excel',
      'Instant search built for Spanish|Búsqueda instantánea en español',
    ],
    pending: [
      'Production recipe per product|Receta de producción por producto',
      'Production cost per unit|Costo de producción por unidad',
      'Production orders with lot and cost|Órdenes de producción con lote y costo',
      'Process stages with time and cost|Etapas del proceso con tiempo y costo',
      'Real margin per product|Margen real por producto',
      'Margin alert when materials go up|Alerta de margen si sube un insumo',
      'Material requirements from the sales plan|Explosión de materiales según el plan',
      'Traceability from material to product|Trazabilidad de insumo a producto',
      'Waste control|Control de mermas',
      'Recipe versions with cost history|Versiones de receta con historial de costo',
      'Selling services, with no stock|Venta de servicios, sin stock',
      'Outsourced production|Producción tercerizada',
      'Bundles and composite products|Combos y productos compuestos',
    ],
  },
  {
    id: 'feature-crm',
    icon: 'icon-[fa--users]',
    illustration: '/images/feature-crm.svg',
    title: 'Customers and CRM|Clientes y CRM',
    lead: 'The customer does not end at the receipt: who you spoke to, what you offered, what they bought, and what they still owe.|El cliente no termina en la boleta: con quién habló, qué le ofreció, qué le compró y cuánto le debe.',
    available: [
      'Customers and suppliers with tax or national ID|Clientes y proveedores con RUC o DNI',
      'Search by name or document|Búsqueda por nombre o documento',
      'Customer created from the point of sale|Alta del cliente desde el punto de venta',
      'Sales report per customer|Reporte de ventas por cliente',
    ],
    pending: [
      'Customer profile with their history|Ficha del cliente con su historial',
      'Contacts and people per company|Contactos y personas por empresa',
      'Log of calls, visits, and emails|Bitácora de llamadas, visitas y correos',
      'Calendar and follow-up reminders|Agenda y recordatorios de seguimiento',
      'Opportunity funnel|Embudo de oportunidades',
      'From opportunity to quote to order|De oportunidad a cotización y a pedido',
      'Accounts and targets per salesperson|Cartera y metas por vendedor',
      'Segmentation and prices per segment|Segmentación y precios por segmento',
      'Receivables and due dates|Cuentas por cobrar y vencimientos',
      'Credit line per customer|Línea de crédito por cliente',
      'Inactive-customer alert|Aviso de cliente inactivo',
      'Email and WhatsApp campaigns|Campañas por correo y WhatsApp',
      'Complaints, warranties, and returns|Reclamos, garantías y devoluciones',
      'Loyalty with points and coupons|Fidelización con puntos y cupones',
      'Customer portal|Portal del cliente',
    ],
  },
  {
    id: 'feature-sales',
    icon: 'icon-[fa--shopping-cart]',
    illustration: '/images/feature-sales.svg',
    title: 'Point of sale and sales|Punto de venta y ventas',
    lead: 'Charge in seconds and walk away with the sale, the stock, and the cash register already squared.|Cobre en segundos y quede con la venta, el stock y la caja ya cuadrados.',
    available: [
      'Point of sale with cart and checkout|Punto de venta con carrito y cobro',
      'Payment and delivery registered separately|Cobro y entrega por separado',
      'Credit sales with a due date|Venta al crédito con vencimiento',
      'Stock deducted by lot and serial|Descuento de stock por lote y serie',
      'Detailed sales report with quick search|Reporte de ventas detallado con búsqueda rápida',
      'Sales charts and daily summary|Gráficos de ventas y resumen diario',
      'Sales forecast with seasonality|Proyección de ventas con estacionalidad',
      'Shipping costs per district|Costos de envío por distrito',
    ],
    pending: [
      'Weekly and monthly summary|Resumen semanal y mensual',
      'SUNAT electronic invoicing|Facturación electrónica SUNAT',
      'Sales and purchase ledgers|Libro de ventas y compras',
      'Quotes that become orders|Cotizaciones que pasan a pedido',
      'Returns and cancellations|Devoluciones y anulaciones',
      'Promotions, bundles, and coupons|Promociones, combos y cupones',
      'Ticket printing and WhatsApp delivery|Impresión de ticket y envío por WhatsApp',
      'Barcode scanner and scale|Código de barras y balanza',
      'Targets and commissions per salesperson|Metas y comisiones por vendedor',
      'Selling with no internet|Venta sin internet',
    ],
  },
  {
    id: 'feature-logistics',
    icon: 'icon-[fa--truck]',
    illustration: '/images/feature-logistics.svg',
    title: 'Logistics and purchasing|Logística y compras',
    lead: 'Know what you have, where you have it, and when it has to be restocked.|Sepa qué tiene, dónde lo tiene y cuándo hay que reponerlo.',
    available: [
      'Sites and warehouses with a visual layout|Sedes y almacenes con layout visual',
      'Stock per warehouse, lot, and serial|Stock por almacén, lote y serie',
      'Stock entries and exits with their report|Entradas y salidas con su reporte',
      'Purchase orders and goods receipt|Órdenes de compra y recepción',
      'Purchasing and supplier management|Gestión de compras y proveedores',
      'Supplies and materials|Suministros y materiales',
      'Replenishment planning|Planificación de reposición',
    ],
    pending: [
      'Purchase suggestion from the reorder point|Sugerencia de compra por punto de reorden',
      'Valued stock ledger and average cost|Kardex valorizado y costo promedio',
      'Transfers between warehouses|Transferencias entre almacenes',
      'Physical inventory and cycle counting|Inventario físico y conteo cíclico',
      'Minimum-stock and expiry alerts|Alertas de stock mínimo y vencimiento',
      'Supplier scoring|Evaluación de proveedores',
      'Electronic dispatch note|Guía de remisión electrónica',
      'Materials consumed by production|Consumo de insumos por producción',
    ],
  },
  {
    id: 'feature-finance',
    icon: 'icon-[fa--line-chart]',
    illustration: '/images/feature-finance.svg',
    title: 'Cash and finance|Caja y finanzas',
    lead: 'The money is recorded where it happens, and from there comes the picture of how the business is doing.|El dinero se registra donde ocurre, y de ahí sale la foto del negocio.',
    available: [
      'Cash registers, banks, and transfers|Cajas, bancos y transferencias',
      'Cash count and reconciliation|Cuadre y conciliación de caja',
      'Cash and bank movement report|Reporte de movimientos de caja y banco',
      'Fixed expenses and partial payments|Gastos fijos y pagos parciales',
      'Collecting a sale posts its cash movement|El cobro genera su movimiento de caja',
    ],
    pending: [
      'Projected cash flow|Flujo de caja proyectado',
      'Payables and their scheduling|Cuentas por pagar y su programación',
      'Monthly income statement|Estado de resultados mensual',
      'Balance sheet and financial statements|Balance y estados financieros',
      'Cost centers|Centros de costo',
      'Bank reconciliation from the statement|Conciliación bancaria por extracto',
      'Budget against actual|Presupuesto contra lo real',
      'Tax summary for the accountant|Resumen de impuestos para el contador',
      'Fixed assets and depreciation|Activos fijos y depreciación',
      'Multi-currency with exchange rate|Multimoneda con tipo de cambio',
    ],
  },
  {
    id: 'feature-ecommerce',
    icon: 'icon-[fa--globe]',
    illustration: '/images/feature-ecommerce.svg',
    title: 'E-commerce and website|Comercio electrónico y página web',
    lead: 'Your store is built with AI on the same ERP catalog: what you update in the system is what your customer sees.|Su tienda se arma con IA sobre el mismo catálogo del ERP: lo que actualiza es lo que ve su cliente.',
    available: [
      'Visual builder with more than 20 templates|Constructor visual con más de 20 plantillas',
      'Pages created and edited with AI|Páginas creadas y editadas con IA',
      'Storefront synced with the catalog|Tienda sincronizada con el catálogo',
      'Cart and payment with Culqi|Carrito y pago con Culqi',
      'Your own domain|Dominio propio',
      'Gallery with optimized images|Galería con imágenes optimizadas',
    ],
    pending: [
      'Storefront orders landing in the ERP|El pedido de la tienda entra al ERP',
      'Customer account and order history|Cuenta e historial del cliente',
      'Shipping calculated at checkout|Envío calculado en el checkout',
      'Yape, Plin, and cash on delivery|Yape, Plin y pago contra entrega',
      'Coupons and campaigns|Cupones y campañas',
      'Selling over WhatsApp|Venta por WhatsApp',
      'Confirmation and dispatch emails|Correos de confirmación y despacho',
      'SEO per product|SEO por producto',
      'Product reviews|Reseñas de productos',
      'Catalog on social networks and marketplaces|Catálogo en redes y marketplaces',
    ],
  },
  {
    id: 'feature-ai',
    icon: 'icon-[fa--magic]',
    illustration: '/images/feature-ai.svg',
    title: 'Built-in AI assistant|Asistente de IA integrado',
    lead: 'It does not just answer: it opens the page, filters, and fills the form for you.|No sólo responde: abre la página, filtra y llena el formulario por usted.',
    available: [
      'A chat that operates the ERP for you|Chat que opera el ERP por usted',
      'Website built and edited with AI|Página web construida y editada con IA',
      'Vector image generation|Generación de imágenes vectoriales',
      'API for external agents|API para agentes externos',
      'AI usage per user|Consumo de IA por usuario',
    ],
    pending: [
      'Streaming answers|Respuestas en streaming',
      'Usage quotas|Cuotas de consumo',
      'Natural-language questions about your data|Preguntas en lenguaje natural sobre sus datos',
      'Stockout and falling-sales alerts|Avisos de quiebre de stock y caída de ventas',
      'WhatsApp assistant|Asistente por WhatsApp',
      'Expenses registered from a photo|Gastos registrados desde una foto',
      'Price and restocking suggestions|Sugerencias de precio y reposición',
    ],
  },
  {
    id: 'feature-security',
    icon: 'icon-[fa--shield]',
    illustration: '/images/feature-security.svg',
    title: 'Security, data, and operations|Seguridad, datos y operación',
    lead: 'The information belongs to the business. Take it with you whenever you want, and run Genix wherever you want.|La información es del negocio. Llévesela cuando quiera y corra Genix donde quiera.',
    available: [
      'Users and access profiles|Usuarios y perfiles de acceso',
      'Data isolated per company|Datos aislados por empresa',
      'A full backup you download yourself|Backup completo que usted descarga',
      'Scheduled jobs and server panel|Tareas programadas y panel de servidor',
      'Cloud, your own server, or a single binary|Nube, servidor propio o un solo binario',
      'Interface in Spanish and English|Interfaz en español e inglés',
      'Open source, GPL v3|Código abierto GPL v3',
    ],
    pending: [
      'Audit trail|Bitácora de auditoría',
      'Two-step verification|Verificación en dos pasos',
      'Scheduled automatic backups|Respaldo automático programado',
      'Mobile app|Aplicación móvil',
      'Email and WhatsApp alerts|Avisos por correo y WhatsApp',
      'Migration from Excel or another system|Migración desde Excel u otro sistema',
    ],
  },
]
