package agent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"app/core"

	"github.com/coder/websocket"
)

// Per-tab local-only websocket bridge between the backend (the agent) and each
// open browser tab. Connections are keyed by a TabID string generated by the
// frontend once per page-load and sent on the WS upgrade as `?tab=<id>`.
// CompanyID/UserID may also be sent as query params and stored on the
// connection so the chat session can sanity-check the tab belongs to its user.

type pendingReply struct {
	ch chan replyEnvelope
}

type replyEnvelope struct {
	kind    string // TypeResult | TypeError
	payload json.RawMessage
}

// clientConn holds one tab's WS connection plus its private request-id space
// and pending-reply table. Each tab gets its own idCount so request ids never
// collide across tabs, and per-conn pending so a tab's reconnect failures
// don't poison sibling tabs' in-flight requests.
type clientConn struct {
	tab       string
	companyID int32
	userID    int32
	conn      *websocket.Conn
	writeM    sync.Mutex

	idCount atomic.Uint64

	pendMu  sync.Mutex
	pending map[uint64]*pendingReply
}

var (
	clientsMu  sync.RWMutex
	clients    = map[string]*clientConn{}
	clientWake = map[string]chan struct{}{} // per-tab "fresh connect" channels
)

// HandleWebSocket upgrades the HTTP request and runs the read loop for the
// browser-side agent. Mounted at /ws/agent. The tab is identified by
// `?tab=<TabID>` on the upgrade URL; missing/empty tab → 400.
func HandleWebSocket(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	tab := strings.TrimSpace(q.Get("tab"))
	if tab == "" {
		http.Error(w, "missing ?tab=", http.StatusBadRequest)
		return
	}
	companyID := atoi32(q.Get("company"))
	userID := atoi32(q.Get("user"))

	// Accept any origin: this server only listens on localhost during dev.
	conn, err := websocket.Accept(w, r, &websocket.AcceptOptions{
		InsecureSkipVerify: true,
	})
	if err != nil {
		core.Log("agent.ws accept error::", err)
		return
	}
	// Disable read size cap so screenshot frames (~MBs) survive.
	conn.SetReadLimit(32 * 1024 * 1024)

	cc := &clientConn{
		tab:       tab,
		companyID: companyID,
		userID:    userID,
		conn:      conn,
		pending:   map[uint64]*pendingReply{},
	}
	registerClient(cc)
	core.Log("agent.ws client connected tab::", tab, " company::", companyID, " user::", userID, " from", r.RemoteAddr)

	defer func() {
		unregisterClient(cc)
		_ = conn.Close(websocket.StatusNormalClosure, "bye")
		core.Log("agent.ws client disconnected tab::", tab)
	}()

	ctx := r.Context()
	for {
		mt, data, err := conn.Read(ctx)
		if err != nil {
			if !errors.Is(err, context.Canceled) {
				core.Log("agent.ws read end tab::", tab, " err::", err)
			}
			return
		}
		if mt != websocket.MessageText {
			continue
		}
		handleIncoming(cc, data)
	}
}

// registerClient installs cc under its tab id, replacing any previous client
// on that same tab (last-connection-wins per tab). Sibling tabs are untouched.
func registerClient(cc *clientConn) {
	clientsMu.Lock()
	prev := clients[cc.tab]
	clients[cc.tab] = cc
	wake, ok := clientWake[cc.tab]
	if !ok {
		wake = make(chan struct{}, 1)
		clientWake[cc.tab] = wake
	}
	clientsMu.Unlock()
	if prev != nil {
		_ = prev.conn.Close(websocket.StatusGoingAway, "replaced")
		prev.failAllPending(errors.New("client reconnected"))
	}
	select {
	case wake <- struct{}{}:
	default:
	}
}

func unregisterClient(cc *clientConn) {
	clientsMu.Lock()
	if clients[cc.tab] == cc {
		delete(clients, cc.tab)
	}
	clientsMu.Unlock()
	cc.failAllPending(errors.New("client disconnected"))
}

func (cc *clientConn) failAllPending(err error) {
	cc.pendMu.Lock()
	defer cc.pendMu.Unlock()
	errPayload, _ := json.Marshal(struct{ Message string }{err.Error()})
	for id, p := range cc.pending {
		select {
		case p.ch <- replyEnvelope{kind: TypeError, payload: errPayload}:
		default:
		}
		delete(cc.pending, id)
	}
}

func handleIncoming(cc *clientConn, raw []byte) {
	// Parse only the envelope; payload stays as RawMessage to be decoded by caller.
	var env struct {
		ID      uint64
		Type    string
		Payload json.RawMessage
	}
	if err := json.Unmarshal(raw, &env); err != nil {
		core.Log("agent.ws bad json tab::", cc.tab, " err::", err, string(raw))
		return
	}

	if env.Type == TypeReady {
		core.Log("agent.ws client signaled ready tab::", cc.tab)
		return
	}

	// Unsolicited events (no matching request) — handled here, not via pending map.
	if env.Type == EventPageContent {
		var page PageContent
		if err := json.Unmarshal(env.Payload, &page); err != nil {
			core.Log("agent.ws pageContent decode error tab::", cc.tab, " err::", err)
			return
		}
		core.Log("agent.ws pageContent received tab::", cc.tab, " components::", len(page.Components), "html bytes::", len(page.HTML))
		fmt.Println("---- agent pageContent components ----")
		for _, c := range page.Components {
			fmt.Printf("  [%d] %s label=%q methods=%v\n", c.ID, c.Type, c.Label, c.Methods)
		}
		fmt.Println("---- end agent pageContent components ----")
		fmt.Println("---- raw HTML data-id occurrences ----")
		fmt.Println("  data-id count:", strings.Count(page.HTML, "data-id"))
		if idx := strings.Index(page.HTML, "data-id"); idx >= 0 {
			end := idx + 80
			if end > len(page.HTML) {
				end = len(page.HTML)
			}
			fmt.Printf("  first occurrence: %q\n", page.HTML[idx:end])
		}
		fmt.Println("---- end raw HTML data-id occurrences ----")
		parsed, err := ParsePageHTML(page.HTML, page.Components)
		if err != nil {
			core.Log("agent.ws pageContent parse error tab::", cc.tab, " err::", err)
			return
		}
		fmt.Println("---- agent pageContent HTML ----")
		fmt.Println(parsed)
		fmt.Println("---- end agent pageContent HTML ----")
		return
	}

	if env.ID == 0 {
		core.Log("agent.ws message without id tab::", cc.tab, " type::", env.Type)
		return
	}

	cc.pendMu.Lock()
	p, ok := cc.pending[env.ID]
	if ok {
		delete(cc.pending, env.ID)
	}
	cc.pendMu.Unlock()

	if !ok {
		core.Log("agent.ws reply with no waiter tab::", cc.tab, " id::", env.ID, " type::", env.Type)
		return
	}
	select {
	case p.ch <- replyEnvelope{kind: env.Type, payload: env.Payload}:
	default:
	}
}

// lookupClient returns the connection for tab, or nil if no client is
// currently registered for it.
func lookupClient(tab string) *clientConn {
	clientsMu.RLock()
	defer clientsMu.RUnlock()
	return clients[tab]
}

// IsConnected reports whether tab has an active browser client.
func IsConnected(tab string) bool {
	return lookupClient(tab) != nil
}

// ConnectedTabs returns the list of currently-connected tab ids. Used by the
// HTTP endpoint to pick a unique tab when the caller doesn't supply `?tab=`.
func ConnectedTabs() []string {
	clientsMu.RLock()
	defer clientsMu.RUnlock()
	out := make([]string, 0, len(clients))
	for tab := range clients {
		out = append(out, tab)
	}
	return out
}

// ResolveTab returns explicit if non-empty, otherwise the unique connected
// tab. Errors when no tabs are connected or more than one is connected and
// the caller didn't disambiguate.
func ResolveTab(explicit string) (string, error) {
	explicit = strings.TrimSpace(explicit)
	if explicit != "" {
		if !IsConnected(explicit) {
			return "", fmt.Errorf("tab %q is not connected", explicit)
		}
		return explicit, nil
	}
	tabs := ConnectedTabs()
	switch len(tabs) {
	case 0:
		return "", errors.New("no agent client connected")
	case 1:
		return tabs[0], nil
	default:
		return "", fmt.Errorf("multiple tabs connected (%d) — pass ?tab=<id>", len(tabs))
	}
}

// WaitForClient blocks until tab has a connected client or ctx is done.
func WaitForClient(ctx context.Context, tab string) error {
	if IsConnected(tab) {
		return nil
	}
	clientsMu.Lock()
	wake, ok := clientWake[tab]
	if !ok {
		wake = make(chan struct{}, 1)
		clientWake[tab] = wake
	}
	clientsMu.Unlock()
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-wake:
			if IsConnected(tab) {
				return nil
			}
		}
	}
}

// request is the low-level RPC: send a command to tab, wait for the reply.
// The reply's payload is decoded into `out` on success.
func request(ctx context.Context, tab, cmdType string, payload any, out any) error {
	cc := lookupClient(tab)
	if cc == nil {
		return fmt.Errorf("no agent client connected for tab %q", tab)
	}

	id := cc.idCount.Add(1)
	msg := Message{ID: id, Type: cmdType, Payload: payload}
	data, err := json.Marshal(msg)
	if err != nil {
		return fmt.Errorf("marshal command: %w", err)
	}

	p := &pendingReply{ch: make(chan replyEnvelope, 1)}
	cc.pendMu.Lock()
	cc.pending[id] = p
	cc.pendMu.Unlock()

	cleanup := func() {
		cc.pendMu.Lock()
		delete(cc.pending, id)
		cc.pendMu.Unlock()
	}

	cc.writeM.Lock()
	writeCtx, cancelWrite := context.WithTimeout(ctx, 10*time.Second)
	err = cc.conn.Write(writeCtx, websocket.MessageText, data)
	cancelWrite()
	cc.writeM.Unlock()
	if err != nil {
		cleanup()
		return fmt.Errorf("ws write: %w", err)
	}

	select {
	case <-ctx.Done():
		cleanup()
		return ctx.Err()
	case env := <-p.ch:
		if env.kind == TypeError {
			var e struct {
				Message string
			}
			_ = json.Unmarshal(env.payload, &e)
			if e.Message == "" {
				e.Message = "agent error"
			}
			return errors.New(e.Message)
		}
		if out != nil && len(env.payload) > 0 {
			if err := json.Unmarshal(env.payload, out); err != nil {
				return fmt.Errorf("decode payload: %w", err)
			}
		}
		return nil
	}
}

// atoi32 parses a base-10 int32 from s, returning 0 on any error. Used for
// the optional company/user query params on the WS upgrade — invalid values
// are tolerated (they become 0) since the chat session validates ownership
// separately.
func atoi32(s string) int32 {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	var n int32
	for _, c := range s {
		if c < '0' || c > '9' {
			return 0
		}
		n = n*10 + int32(c-'0')
	}
	return n
}

// Drain ensures Reader/Writer are not leaked; coder/websocket auto-handles
// pings, but we keep this helper for documentation/symmetry.
var _ = io.Discard
