package agent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"app/core"
)

// Per-tab local-only SSE+POST bridge between the backend (the agent) and each
// open browser tab. Server→browser traffic (page commands AND chat events)
// rides a single Server-Sent-Events stream; browser→backend traffic (command
// replies, unsolicited events, chat user messages) rides POST /agent/in.
// Connections are keyed by a TabID string generated by the frontend once per
// page-load and sent on the stream URL as `?tab=<id>`. CompanyID/UserID/Path
// may also be sent as query params and stored on the connection so the chat
// session can seed itself from the same tab.

type pendingReply struct {
	ch chan replyEnvelope
}

type replyEnvelope struct {
	kind    string // TypeResult | TypeError
	payload json.RawMessage
}

// clientConn holds one tab's SSE stream plus its private request-id space and
// pending-reply table. Each tab gets its own idCount so request ids never
// collide across tabs, and per-conn pending so a tab's reconnect failures
// don't poison sibling tabs' in-flight requests. `send` carries pre-framed SSE
// payloads to the stream's writer goroutine; `closed` is shut when the stream
// ends so blocked pushes unblock.
type clientConn struct {
	tab       string
	companyID int32
	userID    int32
	path      string // SPA path at stream-open time; seeds the chat session route

	send      chan []byte
	closed    chan struct{}
	closeOnce sync.Once

	idCount atomic.Uint64

	pendMu  sync.Mutex
	pending map[uint64]*pendingReply
}

var (
	clientsMu  sync.RWMutex
	clients    = map[string]*clientConn{}
	clientWake = map[string]chan struct{}{} // per-tab "fresh connect" channels
)

// close shuts the stream's closed channel exactly once so pushers unblock and
// the writer goroutine returns.
func (cc *clientConn) close() {
	cc.closeOnce.Do(func() { close(cc.closed) })
}

// push frames data as a single SSE `data:` event and hands it to the writer
// goroutine. json.Marshal output is single-line, so the `data: <json>\n\n`
// framing is always well-formed. Bounded wait: if the stream's buffer stays
// full (slow/stuck client) we give up rather than block the caller (a page RPC
// or a chat status push) forever.
func (cc *clientConn) push(data []byte) error {
	frame := make([]byte, 0, len(data)+8)
	frame = append(frame, "data: "...)
	frame = append(frame, data...)
	frame = append(frame, '\n', '\n')
	t := time.NewTimer(10 * time.Second)
	defer t.Stop()
	select {
	case cc.send <- frame:
		return nil
	case <-cc.closed:
		return errors.New("stream closed")
	case <-t.C:
		return errors.New("stream send timeout")
	}
}

// HandleStream opens the per-tab SSE stream that carries every server→browser
// message. Mounted at `GET /agent/stream`. The tab is identified by
// `?tab=<TabID>`; missing/empty → 400. Runs until the request context is done
// or the stream is replaced by a fresh connect on the same tab.
func HandleStream(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	tab := strings.TrimSpace(q.Get("tab"))
	if tab == "" {
		http.Error(w, "missing ?tab=", http.StatusBadRequest)
		return
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "streaming unsupported", http.StatusInternalServerError)
		return
	}

	cc := &clientConn{
		tab:       tab,
		companyID: atoi32(q.Get("company")),
		userID:    atoi32(q.Get("user")),
		path:      strings.TrimSpace(q.Get("path")),
		send:      make(chan []byte, 64),
		closed:    make(chan struct{}),
		pending:   map[uint64]*pendingReply{},
	}

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	// Defeat reverse-proxy response buffering (nginx honours this) so events
	// reach the browser immediately instead of being held back.
	w.Header().Set("X-Accel-Buffering", "no")
	w.WriteHeader(http.StatusOK)
	flusher.Flush()

	registerClient(cc)
	core.Log("agent.sse client connected tab::", shortTabID(tab), " company::", cc.companyID, " user::", cc.userID, " path::", cc.path, " from", r.RemoteAddr)

	defer func() {
		unregisterClient(cc)
		cc.close()
		core.Log("agent.sse client disconnected tab::", shortTabID(tab))
	}()

	ctx := r.Context()
	// Comment-ping keeps idle streams alive through proxy/idle timeouts.
	keepalive := time.NewTicker(20 * time.Second)
	defer keepalive.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-cc.closed:
			// Flush frames queued right before close (e.g. a "replaced" notice
			// pushed by registerClient) so the browser learns why it ended.
			for {
				select {
				case frame := <-cc.send:
					_, _ = w.Write(frame)
					flusher.Flush()
				default:
					return
				}
			}
		case frame := <-cc.send:
			if _, err := w.Write(frame); err != nil {
				core.Log("agent.sse write end tab::", shortTabID(tab), " err::", err)
				return
			}
			flusher.Flush()
		case <-keepalive.C:
			if _, err := io.WriteString(w, ": ping\n\n"); err != nil {
				return
			}
			flusher.Flush()
		}
	}
}

// HandleIn is the single browser→backend POST endpoint (`POST /agent/in`). It
// carries command replies, unsolicited events (ready, pageContent), and chat
// user messages — all discriminated by `Type`. Returns `{}` immediately; chat
// turns run asynchronously.
func HandleIn(w http.ResponseWriter, r *http.Request) {
	tab := strings.TrimSpace(r.URL.Query().Get("tab"))
	if tab == "" {
		writeJSONError(w, http.StatusBadRequest, "missing ?tab=")
		return
	}
	var env struct {
		ID      uint64
		Type    string
		Payload json.RawMessage
	}
	if err := json.NewDecoder(r.Body).Decode(&env); err != nil {
		writeJSONError(w, http.StatusBadRequest, "invalid request body: "+err.Error())
		return
	}
	handleInbound(r.Context(), tab, env.ID, env.Type, env.Payload)
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write([]byte("{}"))
}

// handleInbound dispatches one decoded inbound envelope: chat messages start a
// turn, unsolicited events are logged, and command replies are routed to the
// matching pending waiter on the tab's connection.
func handleInbound(ctx context.Context, tab string, id uint64, typ string, payload json.RawMessage) {
	switch typ {
	case TypeReady:
		// Ready is the browser's first proof that it opened the stream and
		// registered its page diagnostics.
		core.Log("agent.sse client signaled ready tab::", shortTabID(tab), " payload::", core.StrCut(string(payload), 500))
		return

	case EventPageContent:
		logPageContent(tab, payload)
		return

	case ChatTypeUserMessage:
		var msg ChatUserMessage
		s := ensureChatSession(tab)
		if err := json.Unmarshal(payload, &msg); err != nil {
			s.sendError("invalid userMessage payload: " + err.Error())
			return
		}
		s.onUserMessage(ctx, msg)
		return
	}

	// Everything else is a reply to a backend-issued command, correlated by id.
	if id == 0 {
		core.Log("agent.sse message without id tab::", shortTabID(tab), " type::", typ)
		return
	}
	cc := lookupClient(tab)
	if cc == nil {
		core.Log("agent.sse reply with no stream tab::", shortTabID(tab), " id::", id, " type::", typ)
		return
	}
	cc.pendMu.Lock()
	p, ok := cc.pending[id]
	if ok {
		delete(cc.pending, id)
	}
	cc.pendMu.Unlock()
	if !ok {
		core.Log("agent.sse reply with no waiter tab::", shortTabID(tab), " id::", id, " type::", typ)
		return
	}
	select {
	case p.ch <- replyEnvelope{kind: typ, payload: payload}:
	default:
	}
}

// logPageContent decodes and prints the unsolicited pageContent test push —
// debugging aid for confirming the browser-side snapshot pipeline.
func logPageContent(tab string, payload json.RawMessage) {
	var page PageContent
	if err := json.Unmarshal(payload, &page); err != nil {
		core.Log("agent.sse pageContent decode error tab::", shortTabID(tab), " err::", err)
		return
	}
	core.Log("agent.sse pageContent received tab::", shortTabID(tab), " components::", len(page.Components), "html bytes::", len(page.HTML))
	parsed, err := ParsePageHTML(page.HTML, page.Components)
	if err != nil {
		core.Log("agent.sse pageContent parse error tab::", shortTabID(tab), " err::", err)
		return
	}
	fmt.Println("---- agent pageContent HTML ----")
	fmt.Println(parsed)
	fmt.Println("---- end agent pageContent HTML ----")
}

// registerClient installs cc under its tab id, replacing any previous client
// on that same tab (last-connection-wins per tab). Sibling tabs are untouched.
func registerClient(cc *clientConn) {
	clientsMu.Lock()
	prev := clients[cc.tab]
	clients[cc.tab] = cc
	wake, ok := clientWake[cc.tab]
	if !ok {
		wake = make(chan struct{}, 1)
		clientWake[cc.tab] = wake
	}
	clientsMu.Unlock()
	if prev != nil {
		// Tell the replaced stream why it's ending so a duplicated tab (which
		// cloned sessionStorage and grabbed this same id) can rotate to a fresh
		// id instead of endlessly ping-ponging the shared one.
		select {
		case prev.send <- []byte("data: {\"Type\":\"replaced\"}\n\n"):
		default:
		}
		prev.close()
		prev.failAllPending(errors.New("client reconnected"))
	}
	select {
	case wake <- struct{}{}:
	default:
	}
}

func unregisterClient(cc *clientConn) {
	clientsMu.Lock()
	if clients[cc.tab] == cc {
		delete(clients, cc.tab)
	}
	clientsMu.Unlock()
	cc.failAllPending(errors.New("client disconnected"))
}

func (cc *clientConn) failAllPending(err error) {
	cc.pendMu.Lock()
	defer cc.pendMu.Unlock()
	errPayload, _ := json.Marshal(struct{ Message string }{err.Error()})
	for id, p := range cc.pending {
		select {
		case p.ch <- replyEnvelope{kind: TypeError, payload: errPayload}:
		default:
		}
		delete(cc.pending, id)
	}
}

// lookupClient returns the connection for tab, or nil if no client is
// currently registered for it.
func lookupClient(tab string) *clientConn {
	clientsMu.RLock()
	defer clientsMu.RUnlock()
	return clients[tab]
}

// IsConnected reports whether tab has an active browser stream.
func IsConnected(tab string) bool {
	return lookupClient(tab) != nil
}

// ConnectedTabs returns the list of currently-connected tab ids. Used by the
// HTTP endpoint to pick a unique tab when the caller doesn't supply `?tab=`.
func ConnectedTabs() []string {
	clientsMu.RLock()
	defer clientsMu.RUnlock()
	out := make([]string, 0, len(clients))
	for tab := range clients {
		out = append(out, tab)
	}
	return out
}

// ResolveTab returns explicit if non-empty, otherwise the unique connected
// tab. Errors when no tabs are connected or more than one is connected and
// the caller didn't disambiguate.
func ResolveTab(explicit string) (string, error) {
	explicit = strings.TrimSpace(explicit)
	if explicit != "" {
		if !IsConnected(explicit) {
			return "", fmt.Errorf("tab %q is not connected", explicit)
		}
		return explicit, nil
	}
	tabs := ConnectedTabs()
	switch len(tabs) {
	case 0:
		return "", errors.New("no agent client connected")
	case 1:
		return tabs[0], nil
	default:
		return "", fmt.Errorf("multiple tabs connected (%d) — pass ?tab=<id>", len(tabs))
	}
}

// WaitForClient blocks until tab has a connected client or ctx is done.
func WaitForClient(ctx context.Context, tab string) error {
	if IsConnected(tab) {
		return nil
	}
	clientsMu.Lock()
	wake, ok := clientWake[tab]
	if !ok {
		wake = make(chan struct{}, 1)
		clientWake[tab] = wake
	}
	clientsMu.Unlock()
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-wake:
			if IsConnected(tab) {
				return nil
			}
		}
	}
}

// request is the low-level RPC: push a command to tab's stream, wait for the
// browser's POSTed reply. The reply's payload is decoded into `out` on success.
func request(ctx context.Context, tab, cmdType string, payload any, out any) error {
	cc := lookupClient(tab)
	if cc == nil {
		core.Log("agent.sse request no-client tab::", shortTabID(tab), " cmd::", cmdType, " connected_tabs::", strings.Join(shortConnectedTabs(), ","))
		return fmt.Errorf("no agent client connected for tab %q", tab)
	}

	id := cc.idCount.Add(1)
	msg := Message{ID: id, Type: cmdType, Payload: payload}
	data, err := json.Marshal(msg)
	if err != nil {
		return fmt.Errorf("marshal command: %w", err)
	}
	core.Log("agent.sse request send tab::", shortTabID(tab), " cmd::", cmdType, " id::", id, " payload_bytes::", len(data), " company::", cc.companyID, " user::", cc.userID)

	p := &pendingReply{ch: make(chan replyEnvelope, 1)}
	cc.pendMu.Lock()
	cc.pending[id] = p
	cc.pendMu.Unlock()

	cleanup := func() {
		cc.pendMu.Lock()
		delete(cc.pending, id)
		cc.pendMu.Unlock()
	}

	if err := cc.push(data); err != nil {
		cleanup()
		core.Log("agent.sse request push-error tab::", shortTabID(tab), " cmd::", cmdType, " id::", id, " err::", err)
		return fmt.Errorf("stream push: %w", err)
	}

	select {
	case <-ctx.Done():
		cleanup()
		core.Log("agent.sse request timeout tab::", shortTabID(tab), " cmd::", cmdType, " id::", id, " err::", ctx.Err())
		return ctx.Err()
	case env := <-p.ch:
		if env.kind == TypeError {
			var e struct {
				Message string
			}
			_ = json.Unmarshal(env.payload, &e)
			if e.Message == "" {
				e.Message = "agent error"
			}
			core.Log("agent.sse request browser-error tab::", shortTabID(tab), " cmd::", cmdType, " id::", id, " err::", e.Message, " payload::", core.StrCut(string(env.payload), 500))
			return errors.New(e.Message)
		}
		core.Log("agent.sse request ok tab::", shortTabID(tab), " cmd::", cmdType, " id::", id, " payload_bytes::", len(env.payload))
		if out != nil && len(env.payload) > 0 {
			if err := json.Unmarshal(env.payload, out); err != nil {
				core.Log("agent.sse request decode-error tab::", shortTabID(tab), " cmd::", cmdType, " id::", id, " err::", err, " payload::", core.StrCut(string(env.payload), 500))
				return fmt.Errorf("decode payload: %w", err)
			}
		}
		return nil
	}
}

func shortConnectedTabs() []string {
	tabs := ConnectedTabs()
	out := make([]string, 0, len(tabs))
	for _, tab := range tabs {
		out = append(out, shortTabID(tab))
	}
	return out
}

// atoi32 parses a base-10 int32 from s, returning 0 on any error. Used for
// the optional company/user query params on the stream URL — invalid values
// are tolerated (they become 0) since the chat session validates ownership
// separately.
func atoi32(s string) int32 {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	var n int32
	for _, c := range s {
		if c < '0' || c > '9' {
			return 0
		}
		n = n*10 + int32(c-'0')
	}
	return n
}
